### PR TITLE
major readme cleanup

### PR DESCRIPTION
**Pull request by stevanlohja**
The intent of this PR is to make the content more lean and concise for new and existing volunteers by:
- reducing the use of first person
- removing out-dated directing on out-dated action items
- removing reiteration (e.g.: we're a decentralized community, no need to give a story about how we don't like governance or how diverse our community is. That's already implied!)
- removing broken links
- condensing information as much as possible (e.g.: Community section)
- adding more information on contributing (e.g.: Open standards)
This page should be about volunteering and foremost giving visitors information to volunteer which is the intention of this PR.
It isn't entirely my place to do much in the Projects section, but that part is a mess that can use a 2nd round of cleanup.

### CODE REVIEW

**Comment by realcodywburns** [comment]
can we merge this with pr #1

**Comment by stevanlohja** [comment]
Yeah

**Comment by lostinblue** [comment]
No this is complete trash

**Comment by lostinblue** [comment]
Anyone who isn't inovlved would best stay way from loading these pages as they could lead you to load an XSS iframe like beef.

**Comment by ghost** [comment]
This PR can be closed @realcodywburns?

**Pull request closed without merging**
